dist: bionic
language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- '1.13'
git:
  depth: 500
install:
- go get github.com/kardianos/govendor
script:
- make
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: "EwbEmaT5jr6FrMfziGOnUMeu8mPzlnlXfmWnZ97DK5MHXazrFXc1SGmxjBVFm+SZiHOhOUfot46ClPgducvCfZcCfpKML8yYcmgyFv2wsHqC1S6YOYGeKD5WpPc9IeNwuG+oARZzZ9KlwAENMXCPWbkUF9HhZpgaqdQR+WgHxMd2ZAUe+FA1I/uVbTTBF8v4g0uO71c4XXEwj5sREZRpnD242YLTh5LGMe/a9oeVKU0fzIwencvlI7YHnooDlM1zQLGPmM6Itj8qQUwXS2rEQd8ZH5Z5tv5ITcLwFUZLDK+emb8GQ2vrFJLGnbId7tpaG1oqLyDcIpf12J3n219g2GsQwRDbK5x9XUD278+j4Q4jQ2WJV5ImsL0vWAkpvFHxQsFrJF0wH+GeVHN2AUYVk8MUjlDMPL8EaDBh/hrIwkZd7qHQPRWZB/maQMcBcHNdxumskMviiJRGtDxq1GGfC+qOgdSHVRdH21jyXSWcLUEh0Sj4V8uwVk8zUItR1SsdY3Bi42IOqoFIAXyAxljZP7sr6H73/IO9uY08nw0SMU5dxdsXU4i2tzSZqadKWCLCAbV0IzujIjPnq+O11xwTm6eD+l/4Y1pSjzyZFjFShEgRxxksqZUdbI5LBWVh1F3Yd4Es5Rw4GcwWu29tJhhvecVWHpFWCa1xQHMa4HcowKA="
  file:
  - bin/darwin/amd64/terraform-provider-drp_$(echo ${TRAVIS_TAG} | sed 's/v//g')_darwin_amd64.zip
  - bin/linux/amd64/terraform-provider-drp_$(echo ${TRAVIS_TAG} | sed 's/v//g')_linux_amd64.zip
  skip_cleanup: true
  on:
    repo: form3tech-oss/terraform-provider-drp
    tags: true
