dist: bionic
language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- "1.10"
git:
  depth: 500
script:
- make build
- ./tools/package.sh
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: uKwH4f/tv36GkcwTvLfrO4AxwQ5CmOHZRhmi1rOLp3bABMsLumtXmsw204w4v6vLB/NA6+Dgp/oIMfnlvTK/aktaEBxYDWG5UIgeTdISvjvwGG2+lEehO7aC1JOwW4jPe9OOqkuhIDuQQeCWfzzRCd0zAtKS426cwMnsvY52AMm9cJdTGSznRbDn1guE5Fjt9YbIClyXHHJ38hlQMq2Rb/dqwjAprtJtHwW0h11Wu+8+dkyf1LjnFq9TOki1iiDBKakgoK+sxsnR57/IEdMZK/BhotkvpdlNyjwJusZbTZ/2F6orsXuqgEkoqYVSgea5Ce01BiA6Jm7VbFRBY41wMpsQDB12zY/58Lc0tfFY0hV+trl/FpPn6y8utVjzQ++rffsk/6tUiFEQnCAHVbYhO16fqY3yBmJeZNhVY5mO30cR0Hf5dUKJjaLBjwfNTxvfjV0BeHDR1qY7XMLgWZYeEtCwQXp0p4BGTd0T83t8X6qnoiA0z4Ys81aWV0dCZlmKveJVvPqaaSASzxje2o6d7u5QmgmiJOblk99NMqeqxsTiRReZZf+LtlVMHmTxa7fi1tfuL8chCVVG2QcTimNRWH3xl2RwTqdypAqTcuwNWtpynb/qtJX5WogXSQZFW6GEEdaB8rd+JF/s03pJ9GeGJah8hn7QbniPNx5B7t+NLCg=
  file:
  - bin/darwin/amd64/terraform-provider-drp_$(echo ${TRAVIS_TAG} | sed 's/v//g')_darwin_amd64.zip
  - bin/linux/amd64/terraform-provider-drp_$(echo ${TRAVIS_TAG} | sed 's/v//g')_linux_amd64.zip
  skip_cleanup: true
  on:
    repo: rackn/terraform-provider-drp
    tags: true
