language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- "1.10"
git:
  depth: 500
install:
- go get github.com/kardianos/govendor
- ./tools/build.sh
- ./tools/package.sh
script:
- make test
- make testacc
- make vendor-status
- make vet
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: ${GITHUB_TOKEN}
  file:
  - bin/darwin/amd64/terraform-provider-drp_${TRAVIS_TAG}_darwin_amd64.zip
  - bin/linux/amd64/terraform-provider-drp_${TRAVIS_TAG}_linux_amd64.zip
  - bin/windows/amd64/terraform-provider-drp_${TRAVIS_TAG}_windows_amd64.zip
  skip_cleanup: true
  on:
    repo: form3tech-oss/terraform-provider-drp
    tags: true