language: go
addons:
  apt:
    packages:
    - sshpass
    - bsdtar
    - p7zip-full
sudo: false
go:
- '1.13'
git:
  depth: 500
install:
- go get github.com/kardianos/govendor
script:
- make
deploy:
- provider: releases
  overwrite: true
  api_key:
    secure: "$GITHUB_TOKEN"
  file:
  - bin/darwin/amd64/terraform-provider-drp_${TRAVIS_TAG}_darwin_amd64.zip
  - bin/linux/amd64/terraform-provider-drp_${TRAVIS_TAG}_linux_amd64.zip
  skip_cleanup: true
  on:
    repo: form3tech-oss/terraform-provider-drp
    tags: true
env:
  global:
    secure: Kpdzou5drOIn75TW1c7wg5lu4vPEReAf3jaLZYKDUESXkFo916wL9qnKrQUtZ75iq27UZB1TKpsN0x8o0JtLwvPZBJylsFkwS5SyUv/EKYRDCh8ODDOGeBqJ+RHJjN5Tl4oNR17ylSD2zuYlKGi1fOtcBa1iC6SdbqhVHYhTqVTqrc0u0GkH6V5H0upsTmKfYg6LcoU5zQZ/R24HRLbGZ2oUyjPfH2UIZoji7hGedKr2qrMpSFrPEz+IjFd/7HbZm/nUro/h1N1p0U0usdIK6jAuRjnw7cEqwyAuc6PFdER2dnCq6krtI1AIZ6ird/1ZARMNqR0u0qls709/St5YjfkHrMwd40jN0Tw/dZanPCJWOi1ZPYJMKLVa4P9QUq02hUJXBCCyDE7vNWODNhHzR22edjkdFqrKXjG/S3ivcHYC3+V7kiT6kQf8rjgtmhgm4WpcqKbuUuJCXzHgoDG5QthzLUE+JVjJ80Y+q9CRMIoVz9mhFRhBvl/UsyupiCGPdHpEVCDTpDZpvpEtQl3SU9A+DcnN9mYLv/sn9HeBc09oRPW4fMSVHfvGCTQWxtvCRPgew3gJ9Av4VBTIgY7D+vg63y68MPBmq+bbR6nYMWDqS1K6PTpKFyzjnyZN+QPyQ8FfGvYCzxIWxZpgUm+vKD5kWHqxeDDkTbERGack8oQ=
