name: Test
on:
  push:
  pull_request:
jobs:
  setup-drp:
    name: Setup DRP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
        with:
          fetch-depth: 0
      - name: Setup DRP
        run: |
          curl -fsSL get.rebar.digital/stable | bash -s -- install --isolated --version=stable
      - name: Upload artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: drp
          path: |
            bin/**/*
            assets
            drp-data
            tools
  acceptance:
    name: Acc Test for Terraform ${{ matrix.tf_version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tf_version: ["1.4", "1.5", "1.6", "1.7"]
      fail-fast: false
    needs: setup-drp
    steps:
      - name: Checkout
        uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1
        with:
          fetch-depth: 0
      - name: Download artifact
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: drp
      - name: Set up Go
        uses: actions/setup-go@4d34df0c2316fe8122ab82dc22947d607c0c91f9 # v4.0.0
        with:
          go-version-file: go.mod
      - name: Configure DRP
        run: |
          chmod +x $(pwd)/bin/linux/amd64/dr-provision
          ln -s $(pwd)/bin/linux/amd64/dr-provision /usr/local/bin/dr-provision
          dr-provision --version
      - uses: hashicorp/setup-terraform@633666f66e0061ca3b725c73b2ec20cd13a8fdd1 # v2.0.3
        with:
          terraform_version: ~${{ matrix.tf_version }}
          terraform_wrapper: false
      - name: Run tests
        env:
          TF_ACC: 1
          TF_ACC_LOG: trace
          LOG_LEVEL: debug
          RS_KEY: rocketskates:r0cketsk8ts
          RS_DISABLE_DNS: true
        run: |
          go test -v ./drpv4 -cover -timeout 30m -count 1
